const SearchActionTypes = {
  LOADING: 'LOADING',
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',  
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE'
};

export default SearchActionTypes; 